"use strict";
//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
var useCase1Pk_1 = require("./useCase1Pk");
var UseCase1 = (function () {
    function UseCase1() {
        this.id = new useCase1Pk_1.UseCase1Pk();
    }
    return UseCase1;
}());
exports.UseCase1 = UseCase1;
//# sourceMappingURL=useCase1.js.map