//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/compositepk.ts.cpk.vm
//
"use strict";
var UseCase1Pk = (function () {
    function UseCase1Pk() {
    }
    return UseCase1Pk;
}());
exports.UseCase1Pk = UseCase1Pk;
//# sourceMappingURL=useCase1Pk.js.map