//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
"use strict";
var UseCase2 = (function () {
    function UseCase2() {
    }
    return UseCase2;
}());
exports.UseCase2 = UseCase2;
//# sourceMappingURL=useCase2.js.map