"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.service.ts.e.vm
//
var core_1 = require('@angular/core');
var http_1 = require('@angular/http');
var Observable_1 = require('rxjs/Observable');
var message_service_1 = require('../../service/message.service');
var paging_1 = require('../../support/paging');
var UserService = (function () {
    function UserService(http, messageService) {
        this.http = http;
        this.messageService = messageService;
        this.options = new http_1.RequestOptions({ headers: new http_1.Headers({ 'Content-Type': 'application/json' }) });
    }
    /**
     * Get a User by id.
     */
    UserService.prototype.getUser = function (id) {
        return this.http.get('/api/users/' + id)
            .map(function (response) { return response.json(); })
            .catch(this.handleError);
    };
    /**
     * Update the passed user.
     */
    UserService.prototype.update = function (user) {
        var body = JSON.stringify(user);
        return this.http.put('/api/users/', body, this.options)
            .map(function (response) { return response.json(); })
            .catch(this.handleError);
    };
    /**
     * Load a page (for paginated datatable) of User using the passed
     * user as an example for the search by example facility.
     */
    UserService.prototype.getPage = function (user, event) {
        var req = new paging_1.PageRequestByExample(user, event);
        var body = JSON.stringify(req);
        return this.http.post('/api/users/page', body, this.options)
            .map(function (response) {
            var pr = response.json();
            return new paging_1.PageResponse(pr.totalPages, pr.totalElements, pr.content);
        })
            .catch(this.handleError);
    };
    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by UserCompleteComponent.
     */
    UserService.prototype.complete = function (query) {
        var body = JSON.stringify({ 'query': query, 'maxResults': 10 });
        return this.http.post('/api/users/complete', body, this.options)
            .map(function (response) { return response.json(); })
            .catch(this.handleError);
    };
    /**
     * Delete an User by id.
     */
    UserService.prototype.delete = function (id) {
        return this.http.delete('/api/users/' + id).catch(this.handleError);
    };
    // sample method from angular doc
    UserService.prototype.handleError = function (error) {
        // TODO: seems we cannot use messageService from here...
        var errMsg = (error.message) ? error.message :
            error.status ? "Status: " + error.status + " - Text: " + error.statusText : 'Server error';
        console.error(errMsg); // log to console instead
        return Observable_1.Observable.throw(errMsg);
    };
    UserService = __decorate([
        core_1.Injectable(), 
        __metadata('design:paramtypes', [http_1.Http, message_service_1.MessageService])
    ], UserService);
    return UserService;
}());
exports.UserService = UserService;
//# sourceMappingURL=user.service.js.map