//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/compositepk.ts.cpk.vm
//
"use strict";
var UseCase3Pk = (function () {
    function UseCase3Pk() {
    }
    return UseCase3Pk;
}());
exports.UseCase3Pk = UseCase3Pk;
//# sourceMappingURL=useCase3Pk.js.map