"use strict";
//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
var useCase3Pk_1 = require("./useCase3Pk");
var UseCase3 = (function () {
    function UseCase3() {
        this.id = new useCase3Pk_1.UseCase3Pk();
    }
    return UseCase3;
}());
exports.UseCase3 = UseCase3;
//# sourceMappingURL=useCase3.js.map