"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/app.module.ts.p.vm
//
var core_1 = require('@angular/core');
var platform_browser_1 = require('@angular/platform-browser');
var forms_1 = require('@angular/forms');
var http_1 = require('@angular/http');
var primeng_1 = require('primeng/primeng');
var primeng_2 = require('primeng/primeng');
var app_component_1 = require('./app.component');
var home_component_1 = require('./home.component');
var message_service_1 = require('./service/message.service');
var app_routes_1 = require('./app.routes');
var email_validator_1 = require('./support/email.validator');
var author_service_1 = require('./entities/author/author.service');
var author_list_component_1 = require('./entities/author/author-list.component');
var author_detail_component_1 = require('./entities/author/author-detail.component');
var author_line_component_1 = require('./entities/author/author-line.component');
var author_auto_complete_component_1 = require('./entities/author/author-auto-complete.component');
var book_service_1 = require('./entities/book/book.service');
var book_list_component_1 = require('./entities/book/book-list.component');
var book_detail_component_1 = require('./entities/book/book-detail.component');
var book_line_component_1 = require('./entities/book/book-line.component');
var book_auto_complete_component_1 = require('./entities/book/book-auto-complete.component');
var project_service_1 = require('./entities/project/project.service');
var project_list_component_1 = require('./entities/project/project-list.component');
var project_detail_component_1 = require('./entities/project/project-detail.component');
var project_line_component_1 = require('./entities/project/project-line.component');
var project_auto_complete_component_1 = require('./entities/project/project-auto-complete.component');
var role_service_1 = require('./entities/role/role.service');
var role_list_component_1 = require('./entities/role/role-list.component');
var role_detail_component_1 = require('./entities/role/role-detail.component');
var role_line_component_1 = require('./entities/role/role-line.component');
var role_auto_complete_component_1 = require('./entities/role/role-auto-complete.component');
var useCase1_service_1 = require('./entities/useCase1/useCase1.service');
var useCase1_list_component_1 = require('./entities/useCase1/useCase1-list.component');
var useCase1_detail_component_1 = require('./entities/useCase1/useCase1-detail.component');
var useCase1_line_component_1 = require('./entities/useCase1/useCase1-line.component');
var useCase1_auto_complete_component_1 = require('./entities/useCase1/useCase1-auto-complete.component');
var useCase2_service_1 = require('./entities/useCase2/useCase2.service');
var useCase2_list_component_1 = require('./entities/useCase2/useCase2-list.component');
var useCase2_detail_component_1 = require('./entities/useCase2/useCase2-detail.component');
var useCase2_line_component_1 = require('./entities/useCase2/useCase2-line.component');
var useCase2_auto_complete_component_1 = require('./entities/useCase2/useCase2-auto-complete.component');
var useCase3_service_1 = require('./entities/useCase3/useCase3.service');
var useCase3_list_component_1 = require('./entities/useCase3/useCase3-list.component');
var useCase3_detail_component_1 = require('./entities/useCase3/useCase3-detail.component');
var useCase3_line_component_1 = require('./entities/useCase3/useCase3-line.component');
var useCase3_auto_complete_component_1 = require('./entities/useCase3/useCase3-auto-complete.component');
var user_service_1 = require('./entities/user/user.service');
var user_list_component_1 = require('./entities/user/user-list.component');
var user_detail_component_1 = require('./entities/user/user-detail.component');
var user_line_component_1 = require('./entities/user/user-line.component');
var user_auto_complete_component_1 = require('./entities/user/user-auto-complete.component');
var AppModule = (function () {
    function AppModule() {
    }
    AppModule = __decorate([
        core_1.NgModule({
            imports: [
                // angular
                platform_browser_1.BrowserModule,
                forms_1.FormsModule,
                http_1.HttpModule,
                // primeng
                primeng_1.ConfirmDialogModule,
                primeng_1.FileUploadModule,
                primeng_1.PanelModule,
                primeng_1.GrowlModule,
                primeng_1.MenubarModule,
                primeng_1.DialogModule,
                primeng_1.ButtonModule,
                primeng_1.AutoCompleteModule,
                primeng_1.DataTableModule,
                primeng_1.SharedModule,
                primeng_1.DropdownModule,
                primeng_1.PickListModule,
                primeng_1.CheckboxModule,
                primeng_1.TriStateCheckboxModule,
                primeng_1.InputTextModule,
                primeng_1.InputTextareaModule,
                primeng_1.CalendarModule,
                primeng_1.PasswordModule,
                primeng_1.TabViewModule,
                // our app
                app_routes_1.routing
            ],
            declarations: [
                app_component_1.AppComponent,
                home_component_1.HomeComponent,
                email_validator_1.EmailValidator,
                author_list_component_1.AuthorListComponent,
                author_detail_component_1.AuthorDetailComponent,
                author_line_component_1.AuthorLineComponent,
                author_auto_complete_component_1.AuthorCompleteComponent,
                book_list_component_1.BookListComponent,
                book_detail_component_1.BookDetailComponent,
                book_line_component_1.BookLineComponent,
                book_auto_complete_component_1.BookCompleteComponent,
                project_list_component_1.ProjectListComponent,
                project_detail_component_1.ProjectDetailComponent,
                project_line_component_1.ProjectLineComponent,
                project_auto_complete_component_1.ProjectCompleteComponent,
                role_list_component_1.RoleListComponent,
                role_detail_component_1.RoleDetailComponent,
                role_line_component_1.RoleLineComponent,
                role_auto_complete_component_1.RoleCompleteComponent,
                useCase1_list_component_1.UseCase1ListComponent,
                useCase1_detail_component_1.UseCase1DetailComponent,
                useCase1_line_component_1.UseCase1LineComponent,
                useCase1_auto_complete_component_1.UseCase1CompleteComponent,
                useCase2_list_component_1.UseCase2ListComponent,
                useCase2_detail_component_1.UseCase2DetailComponent,
                useCase2_line_component_1.UseCase2LineComponent,
                useCase2_auto_complete_component_1.UseCase2CompleteComponent,
                useCase3_list_component_1.UseCase3ListComponent,
                useCase3_detail_component_1.UseCase3DetailComponent,
                useCase3_line_component_1.UseCase3LineComponent,
                useCase3_auto_complete_component_1.UseCase3CompleteComponent,
                user_list_component_1.UserListComponent,
                user_detail_component_1.UserDetailComponent,
                user_line_component_1.UserLineComponent,
                user_auto_complete_component_1.UserCompleteComponent
            ],
            providers: [
                author_service_1.AuthorService,
                book_service_1.BookService,
                project_service_1.ProjectService,
                role_service_1.RoleService,
                useCase1_service_1.UseCase1Service,
                useCase2_service_1.UseCase2Service,
                useCase3_service_1.UseCase3Service,
                user_service_1.UserService,
                message_service_1.MessageService,
                primeng_2.ConfirmationService
            ],
            bootstrap: [app_component_1.AppComponent]
        }), 
        __metadata('design:paramtypes', [])
    ], AppModule);
    return AppModule;
}());
exports.AppModule = AppModule;
//# sourceMappingURL=app.module.js.map